
spring:
  application:
    name: resultset-with-josson-demo


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate: 
      ddl-auto: none  # to force use schema.sql and data.sql files
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  sql:
    init:
      mode: always